-- -*- mode: lua; coding: windows-1251-dos -*-

-----------------------------------------------------------------------
-- Модуль учета, респавна аномалий и спавна артов на месте удаленных аномалий после выброса
-- Унаследован от ogsm_anomaly авторы DEXXX, Offbar
-- Dusty79, KamikaZze (c) OGS Evolution Team
-- KRodin (с) 2016: Выкинул всё лишнее, оптимизировал скрипт.
-- Используется некоторый код Dsh мода.
-- version 3.0 (23/11/2016)
-----------------------------------------------------------------------

function attach(sm)
	sm:subscribe({signal = "on_spawn", fun = this.anom_update})
	sm:subscribe({signal = "on_after_blowout", fun = this.on_after_blowout})
	sm:subscribe({signal = "on_anomaly_spawn", fun = this.on_anomaly_spawn})
	sm:subscribe({signal = "on_anomaly_net_destroy", fun = this.on_anomaly_net_destroy})
end

local DISABLE_ANOMS_RESPAWN = false --DBG

local list_anom_id = {}
local lvids_forbidden = {}
local position_forbidden = {}
--
local anti_spawn_zones = {}
local anom_list = {} --В этой таблице находятся только онлайновые аномалии.
local get_lists_inited = false
--
local level_anoms = { --Локации, на которых можно респавнить аномалии после выброса. Значение - походу коэффициент для рассчёта кол-ва аномалий.
	l01_escape     = { 35, 45},   -- 83 + 9
	l02_garbage    = { 40, 45},   -- 88 + 10
	l03_agroprom   = { 30, 40},   -- 82
	l04_darkvalley = { 40, 45},   -- 31
	l05_bar        = {  3,  8},   --  8
	l06_rostok     = { 25, 30},   -- 26 + 17 + 15
	l08_yantar     = { 30, 40},   --  0
	l07_military   = { 40, 45},   -- 60 + 6
	l10_radar      = { 50, 55},   -- 68
	l11_pripyat    = { 35, 40},   -- 38 + 10
	l12_stancia    = { 35, 40},   -- 34
}
--
local excluded_anoms = { --Секции и имена аномалий, которые запрещено удалять после выброса.
--========================[Секции]=========================
	--Секции жгучего пуха
	['zone_burning_fuzz'] = true,
	['zone_burning_fuzz1'] = true,
	['zone_burning_fuzz_weak'] = true,
	['zone_burning_fuzz_average'] = true,
	['zone_burning_fuzz_strong'] = true,
	['zone_burning_fuzz_bottom_weak'] = true,
	['zone_burning_fuzz_bottom_average'] = true,
	['zone_burning_fuzz_bottom_strong'] = true,
	--Секции очагов радиации
	['zone_radioactive'] = true,
	['zone_radioactive_weak'] = true,
	['zone_radioactive_average'] = true,
	['zone_radioactive_strong'] = true,
	['zone_radioactive_killing'] = true,
	['handmade_zone_radioactive'] = true,
	--
	["zone_ameba"] = true, --секция какой-то уникальной аномалии
	["zone_hvatalka"] = true, --секция хваталок
	["zone_liana"] = true, --секция лиан
--===========================================================
--=======================[Далее имена]=======================
	["esc_tutorial_mincer_01"] = true,
	["esc_tutorial_mincer_01_0000"] = true,
	["esc_tutorial_mosquito_bald_01"] = true,
	["esc_tutorial_mosquito_bald_01_0000"] = true,

	["pri_zone_gravi_zone_average_secret_2"] = true,
	["pri_zone_gravi_zone_strong_secret_1"] = true,
	["pri_zone_mincer_strong_secret_1"] = true,
	["pri_zone_mosquito_bald_average_secret_2"] = true,
	["pri_zone_mosquito_bald_strong_secret_1"] = true,
	["pri_zone_mosquito_bald_strong_secret_2"] = true,

	["esc_zone_witches_galantine"] = true,
	["esc_zone_witches_galantine_0000"] = true,
	["esc_zone_witches_galantine_0001"] = true,
	["esc_zone_witches_galantine_0002"] = true,
	["esc_zone_witches_galantine_0003"] = true,
	["esc_zone_witches_galantine_0004"] = true,
	["esc_zone_witches_galantine_0005"] = true,
	["esc_zone_witches_galantine_0006"] = true,
	["esc_zone_witches_galantine_0007"] = true,

	["gar_zone_mosquito_bald_weak_noart_0000"] = true,
	["gar_zone_mosquito_bald_weak_noart_0001"] = true,
	["gar_zone_mosquito_bald_weak_noart_0002"] = true,
	["gar_zone_mosquito_bald_weak_noart_0003"] = true,
	["gar_zone_mosquito_bald_weak_noart_0004"] = true,
	["gar_zone_mosquito_bald_weak_noart_0005"] = true,
	["gar_zone_mosquito_bald_weak_noart_0006"] = true,
	["gar_zone_mosquito_bald_weak_noart_0007"] = true,
	["gar_zone_mosquito_bald_weak_noart_0008"] = true,
	["gar_zone_mosquito_bald_weak_noart_0009"] = true,
	["gar_zone_mosquito_bald_weak_noart_0010"] = true,	
	["gar_zone_mincer_strong_0003"] = true,
	["gar_zone_mincer_strong_0007"] = true,
	["gar_zone_mincer_strong_0012"] = true,

	["rostok_zone_buzz"] = true,

	["rostok_zone_witches_galantine_average"] = true,
	["rostok_zone_witches_galantine_average_0000"] = true,
	["rostok_zone_witches_galantine_average_0001"] = true,
	["rostok_zone_witches_galantine_average_0002"] = true,
	["rostok_zone_witches_galantine_average_0003"] = true,
	["rostok_zone_witches_galantine_average_0004"] = true,

	--Тоннель с жарками на ДТ
	["rostok_zone_zharka_static_average"] = true,
	["rostok_zone_zharka_static_average_0000"] = true,
	["rostok_zone_zharka_static_average_0001"] = true,
	["rostok_zone_zharka_static_average_0002"] = true,
	["rostok_zone_zharka_static_average_0003"] = true,
	["rostok_zone_zharka_static_average_0004"] = true,
	["rostok_zone_zharka_static_average_0005"] = true,
	["rostok_zone_zharka_static_average_0006"] = true,
	["rostok_zone_zharka_static_average_0007"] = true,
	["rostok_zone_zharka_static_average_0008"] = true,
	["rostok_zone_zharka_static_average_0009"] = true,
	["rostok_zone_zharka_static_average_0010"] = true,
	["rostok_zone_zharka_static_average_0011"] = true,
	["rostok_zone_zharka_static_average_0012"] = true,
	["rostok_zone_zharka_static_average_0013"] = true,
	["rostok_zone_zharka_static_average_0014"] = true,
	["rostok_zone_zharka_static_average_0015"] = true,
	["rostok_zone_zharka_static_average_0016"] = true,
	["rostok_zone_zharka_static_average_0017"] = true,
	["rostok_zone_zharka_static_average_0018"] = true,
	["rostok_zone_zharka_static_average_0019"] = true,
	["rostok_zone_zharka_static_average_0020"] = true,
	["rostok_zone_zharka_static_average_0021"] = true,
	["rostok_zone_zharka_static_average_0022"] = true,

	["mil_zone_witches_galantine0000_0000"] = true,
	["mil_zone_witches_galantine0000"] = true,
	["mil_zone_zharka_static_strong"] = true,
	["mil_zone_zharka_static_strong_0000"] = true,
	["mil_zone_zharka_static_strong_0001"] = true,
	["mil_zone_zharka_static_strong_0002"] = true,

--===========================================================
}
local not_anomal_zones = { --Секции объектов, которые созданы на классах аномалий, но не являются аномалиями. Они не добавляются в anom_list и не удаляются после выброса.
	--Туман
	["zone_fog"] = true,
	["zone_fog_ground"] = true,
	["zone_fog_move"] = true,
	["zone_fog_cigarette"] = true,
	["zone_fog_indoor"] = true,
	--Огонь
	["zone_campfire_mp_nolight"] = true,
	["zone_campfire_grill"] = true,
	["zone_flame"] = true,
	["zone_flame_small"] = true,
	--Мины
	["zone_mine_field"] = true,
	--Аномальная зона в саркофаге
	["zone_monolith"] = true,
	--Какая-то аномалия в Припяти
	["zone_no_gravity"] = true,
	["handmade_zone_no_gravity"] = true,
--==================[Телепорты]===================
	['zone_teleport'] = true,
	['zone_teleport_out'] = true,
	['zone_teleport_monolith'] = true,
	['zone_teleport_2'] = true,
--=================================================
}
--Зоны, внутри которых запрещено спавнить аномалии. Надо учитывать, что аномалии автоматически НЕ спавнятся рядом с укрытиями, переходами,
--позициями сталкеров, монстров, аномалий (которые запрещено удалять) и объектов на классах аномалий (мин, и даже туманов? и костров?)
--Все остальные зоны надо вносить в эту таблицу.
local bad_circle_table = {
-- Кордон ---
["l01_escape"] = {
{ 313.16,   3.70, 116.90, 15},	-- лагерь "в поле"
{-156.70, -29.60,-369.30,200},	-- армейский кордон
{20.72,  15.95, 668.35, 45},	-- заброшенный кордон
{162.58,  8.85, 68.50, 20},	-- район вокруг Обелиска
{311.82,3.78,115.06, 20},	-- лагерь хедхантеров за горбом
{2.55,-18.25,-161.43, 20},	-- заброшенный научный лагерь
{-242.65,-8.14,-65.35, 20},	-- район охоты на первого кровососа
{134.47,0.21,339.73, 20},	-- Убежище Андрея
{210.27,2.03,322.07, 20},	-- Упавший в электры вертолёт
{135.00,11.84,230.64, 10},	-- Жигули Лесника на горбе за мостом
{27.28,1.19,24.76, 15},		-- Пост хедхантеров №1
{-99.59,-4.53,-103.60, 15},	-- Пост хедхантеров №2
{32.28,0.20,-74.16, 15},	-- Пост хедхантеров №3
{-243.69,-14.35,-17.47, 10},	-- Аномальная зона
{45.31,-10.85,-33.62, 7},	-- Турист в "Студне"
{-4.71,0.32,6.70, 10},		-- Сгоревший БТР
{-32.93,-6.91,1.71, 5},		-- Рация рядом со сгоревшим БТР-ом
{308.34,14.85,273.36, 5},	-- Позиция сдуревшего новичка с арбалетом
{-230.56,-28.09,-221.08, 25},	-- место охоты на ночного кровососа
{-163.34,-22.58,-207.79, 10},	-- место появления выжившего Овраха
{119.51,1.95,469.29, 20},	-- путь следования Андрея и майора на КПП
{83.37,8.94,607.35, 20},	-- путь следования Андрея и майора на КПП
{18.34,3.28,89.94, 10},		-- место внутри мельницы, где исчезают трое неизвестных
{57.37,-1.27,32.48, 7},		-- место появления киллеров, идущих к мосту
{-176.26,-6.14,-39.53, 5},	-- тело без сознания
{-40.35,-10.25,-73.43, 10},	-- место охоты на пищевого кабана
{183.32,-8.06,-1.70, 8},	-- вещи исчезнувшего на дороге
{6.41,2.38,63.72, 10},		-- мельница с зомбями
{2.07,4.10, 124.55, 20}		-- лежка Волка рядом с мельницей
},

-- Свалка ---
["l02_garbage"] = {
{-16.76,   0.54, 284.90, 10},	-- точка перехода
{-282.50,   3.29, -24.80, 10},	-- точка перехода
{-225.36,  -8.24,-139.30, 35},	-- лагерь за кладбищем техники
{15.16,   0.40, -14.70, 15},	-- автобусная остановка напротив ангара
{31.69,   0.48,-263.05, 25},	-- сценка с Юриком
{36.45,   0.48,-305.70, 10},	-- точка перехода
{-183.00,   0.00,-160.00, 20},	-- старт квестовых бандитов за кладбищем техники
{-100.00,   0.00,-204.00, 10},	-- наблюдатель с биноклем, пасущий бандитов
{275.70,-7.47,1.67, 25},		-- Бак с "Роем" в овражке у дерева
{69.55,1.09,99.32, 20},		-- Убегающий телепорт меж 2 резервуаров
{-184.61,-3.55,109.21, 15},		-- Экскаватор с "Душами" погибших
{-47.20,-0.80,-35.11, 15},		-- Запорожец с "Роем"
{82.18,-0.56,-55.84, 10},		-- Хлюст и его артефакт
{230.96,-1.22,-202.26, 20},		-- Место базирования БТР-а и Мосола
{231.26,-3.15,-26.25, 15},		-- Место базирования Нивы и учёного-посыльного от Пильмана
{156.79,-1.03,-178.19, 10},		-- Гнездо псевдособак на опушке леска
{-185.88,4.00,-65.10, 15},		-- Пост хедхантеров №1
{-137.36,0.40,80.11, 15},			-- Пост хедхантеров №2
{72.91,-0.02,-52.39, 15},			-- Пост хедхантеров №3
{-39.08,20.25,105.41, 10},			-- Аномальная зона
{-267.88,0.40,-14.52, 15},			-- У перехода на Агро(колонна техники)
{-193.20,0.58,9.24, 10},			-- вход в ж\д туннель
{-125.88,-0.62,207.73, 25},			-- Захоронение 335
{-240.49,-3.36,95.33, 20},			-- Братская могила ликвидаторов
{10.67,0.49,-192.75, 6},			-- Разбитый автомобиль у кладбища техники
{183.84,-1.56,-113.33, 10},			-- место стрелки с Тырсой1
{151.79,6.02,-75.32, 10},			-- место стрелки с Тырсой2
{132.40,-3.01,267.54, 20},			-- место содержания пленников
{48.07,0.40,-61.43, 20},			-- стадо собак у дороги
{-5.15,0.40,51.46, 20},			-- стадо тушканов у дороги
{14.96,0.46,236.51, 30},			-- сломанный БТР у перехода в Бар
{-82.00,   0.00,-208.00, 40}		-- Бес, поле боя с бандитами
},

-- Агропром ---
["l03_agroprom"] = {
{76.33,  -0.05,  33.20, 20}, 	-- место боя нейтралов с солдатнёй
{-28.45,-0.63,-177.25, 10}, 	-- убежище местного разведчика
{-112.51,0.49,-28.95, 15}, 	-- "мухи-воры" у прицепа на дороге
{-61.34,-0.02,-1.51, 10}, 	-- позиция Юрия перед входом в подземку
{-160.43,0.03,-305.09, 15}, 	-- место базирования агентов Нунана
{4.95,19.49,203.14, 15}, 	-- место базирования агентов Пильмана
{116.53,2.47,-173.58, 23},			-- Захоронение 
{-82.09,10.69,-109.56, 15},			-- Машина Камеррера
{90.14,10.30,186.10, 5},			-- Зона Маски
{ 173.50,   0.30,   6.70, 10}		-- точка возврата после облёта камеры
},

-- Темная долина ---
["l04_darkvalley"] = {
{  -9.36,   6.80,  98.10, 10},	-- точка перехода
{  39.32,   1.62,  -215.90, 15},	-- вагончик разведчика
{30.82,0.00,-240.85, 4},		-- место приземления вертолетов
{135.45,0.21,-14.85, 10},		-- путь девушки с заправки 1
{136.20,0.25,-71.45, 8},		-- путь девушки с заправки 2
{161.19,-4.71,-76.35, 10},		-- путь девушки с заправки 3
{156.80,-3.32,-120.91, 10},		-- путь девушки с заправки 4
{-118.90,0.03,-450.20, 10},		-- ренегаты у забора фермы
{-139.04,-1.00,-304.81, 18},		-- БТР с зомбированными военными у утёса
{116.50,4.37,-423.19, 15},		-- палатка Ворпала у холма
{-94.89,2.35,-320.78, 15},		-- место спавна химер, нападающих на БТР
{146.05,4.02,-467.36, 20},		-- Аномалия "Три сосны"
{142.83,0.45,-201.11, 15},		-- Старый вагончик у фабрики
{91.14,2.01,-507.77, 15},		-- место базирования Мосола
{-163.66,0.27,-379.88, 15},		-- место базирования агента Пильмана
{54.18,0.04,-220.99, 15},		-- место приземления Хью
{-217.17,   2.00,-183.55, 10}		-- точка перехода
},

-- Бар ---
["l05_bar"] = {
{389.00,  11.23,-419.00, 10},	-- точка перехода
{-30.30,  -6.45, 380.60, 10},	-- точка перехода
{48.00,  -0.20, 142.00, 20},	-- точка перехода
{391.25,12.91,-349.33, 30},	-- аномальный автобус
{306.50,3.35,-146.17, 20},	-- труп вояки и рация
{388.38,19.11,-272.04, 30},	-- место боя со снорками у бензовоза
{160.00,   0.00, 100.00,150}		-- территория
},

-- Дикая территория ---
["l06_rostok"] = {
{-162.27, -11.08,-345.90, 10},	-- точка перехода
{34.96,  -0.57, 139.10, 10},	-- точка перехода
{-280.60,   0.00,  97.70, 10},	-- точка перехода
{-27.35,   0.00, 141.50, 30},	-- пост долговцев на ДТ
{-242.20,   4.00,  50.20, 30},	-- стройка наёмников
--{-106.80,   1.40, 135.50, 20},	-- бульдозер
{-236.37,   0.00,  -9.50, 10}		-- дозорный одиночка (после X-10)
},

-- Армейские склады ---
["l07_military"] = {
{99.65,  -0.30, 304.30, 35},	-- лагерь у Барьера
{-37.07,  -10.98, 201.96, 35},	-- Гравитационная аномалия
{-215.42,  -12.65, 46.83, 30},	-- хутор ВСУ
{-176.82,  -15.58, 375.63, 25},	-- хутор сепаров
{-365.70,  -16.12, 396.63, 25},	-- блокпост на МГ
{-17.91,  -17.44, 163.47, 5},	-- путь Абдуля к барьеру
{-60.92,  -16.78, 171.51, 5},	-- путь Абдуля к барьеру
{-149.95,  -20.04, 112.99, 5},	-- путь Абдуля к барьеру
{-250.89,  -23.62, 103.39, 5},	-- путь Абдуля к барьеру
{-204.52,  4.09, 443.17, 15},	-- разведчик на дереве
{98.62,0.00,302.43, 20},	-- гнездо мутантов
{-112.84,-19.32,295.42, 20},	-- гнездо мутантов
{-91.25,-20.32,230.33, 20},	-- гнездо мутантов
{107.73,-11.36,231.64, 20},	-- гнездо мутантов
{-112.84,-19.32,295.42, 20},	-- гнездо мутантов
{-74.45,-19.36,159.11, 20},	-- гнездо мутантов
{-141.80,-20.91,127.72, 10},	-- остановка
{-188.71,-10.58,135.57, 10},	-- путь Чехова
{-108.48,-19.14,260.26, 15},	-- место сброса груза с вертолета и Хью
{-172.68,-3.02,-7.01, 15},	-- учёные на Ниве
{-74.04,-8.55,405.42, 15},	-- торгаш и вояки на БТР-е
{-65.91,-15.88,238.85, 20},	-- убежище разведчика
{-269.26, -18.10,  236.12, 90}		-- деревенька
},

-- Янтарь ---
["l08_yantar"] = {
{255.40,   6.70,-281.00, 10},	-- точка перехода
{-66.65,  -0.50,-353.40, 10},	-- точка перехода
{161.65,  -7.70, -96.70, 20},	-- лагерь у автобуса
{31.55, -11.70,-272.40, 30},	-- лагерь экологов
{144.22,   -2.10,69.84, 15},	-- заброшенный лагерь у камаза
{3.26,   0.77, -164.70, 20},	-- лазутчик бюреров
{18.04,   1.12, -166.52, 30},	-- место охоты на лазутчика бюреров
{128.24,-1.92,45.00, 10},	-- призраки у камаза
{118.48,   2.27, -29.08, 10},	-- место выхода на связь с Егоровым
{145.30,   -2.08, 68.08, 16},	-- затерянный лагерь разведчика
{46.11,   0.68, -130.84, 10},	-- аномальная зона
{-46.07,   -13.60, -264.67, 10},	-- район замеров на болоте
{42.32,   0.30, -12.39, 60},	-- вся территория завода
{29.98,   -11.64, -276.19, 40},	-- бункер учёных и двор
{122.47,   0.73, -184.75, 8},	-- сгоревший джип на дороге
{90.80,   1.60, -137.16, 8},	-- вход в трансформаторную будку
{-86.29,   -15.43, -198.58, 10},	-- подземный коллектор
{-25.70,   0.80, -10.30, 10}		-- точка перехода
},

-- Радар ---
["l10_radar"] = {
{266.80, -40.00,  64.50,  5},	-- точка на подъёме к антенному комплексу
{251.20, -35.85,  69.50,  5},	-- точка на подъёме к антенному комплексу
{238.30, -28.45,  85.60,  5},	-- точка на подъёме к антенному комплексу
{197.80, -13.00,  84.85, 15},	-- пост на подъёме к антенному комплексу
{140.55,  -4.35,  34.40, 15},	-- пост на подъёме к антенному комплексу
{279.00, -42.40,  57.70, 15},	-- костёр на подъёме к антенному комплексу
{187.40, -12.05,  81.50, 15},	-- костёр на подъёме к антенному комплексу
{107.55,   0.35,  28.10, 20},	-- костёр после подъёма к антенному комплексу
{101.10,   0.65, -46.80, 15},	-- дерево на заборе антенного комплекса
{355.18,   -47.30, -189.71, 20},	-- вертушка в лесу
{351.06,   -50.17, -234.54, 15},	-- место спавна Феникса 1
{403.24,-50.34,-207.48, 10},	-- место спавна Феникса 2
{325.61,-47.36,-166.41, 10},	-- место спавна Феникса 3
{607.67,-51.98,-316.83, 20},	-- КПП на входе
{538.06,-54.50,-88.17, 5},	-- тело в лесу
{515.16,-50.10,-127.57, 5},	-- тело в лесу
{59.77,-3.84,-47.36, 35},	-- территория Антенн
{524.02,-49.86,-122.39, 15},	-- нычка с ПДА экспедиции
{288.24,-51.03,-68.00, 15},	-- нычка с ПДА экспедиции
{633.69,-61.64,-190.18, 15},	-- нычка с ПДА экспедиции			
{8.05,  -0.30, -71.50, 20}		-- вход на территорию антенного комплекса
},

-- Припять ---
["l11_pripyat"] = {
{-112.88, -2.19,  63.97,  10},	-- место спавна кровосаса возле автостанции
{-19.19,12.44,-176.70,  9},	-- позиция снайпера-убийцы Абдуля
{120.13, -0.94,  -22.11,  45},	-- детсад
{-58.79, -0.71,  9.09,  25},	-- площадка с прыгающим мячом
{-112.02, -2.23,  21.10,  40},	-- помещение автовокзала
{-6.96, 2.80,  200.86,  40},	-- помещение актового зала
{-67.34, 3.00,  190.01,  20},	-- место встречи с Апостолом
{31.21, 1.06,  268.89,  10},	-- вход на стадион			
{4.42,  -2.60, -189.41, 10}		-- место смерти Абдуля
},

-- ЧАЭС-1 ---
["l12_stancia"] = {
{959.23, 0.00,  -364.73,  100},	-- островок безопасности перед мостом;
{1012.27, 0.00,  45.69,  10},	-- агент 2
{581.97, 0.10,  -10.91,  10},	-- агент 3
{273.27, 0.40,  -218.41,  10},	-- агент 4
{922.28, 0.40,  -243.11,  10},	-- агент 1
{851.23, -0.10,  -61.44,  10},	-- островок безопасности(3 вагончика)
{976.88, -0.40,  -92.75,  150},	-- первый сектор двора(где вихри)
{387.41,  0.15, -4.36, 10}		-- вход в станцию
},

-- Окраина ---
["predbannik"] = {
{-44.69, 1.54,  354.35,  55},	-- хуторок контрабандистов
{-214.31, 17.91,  246.78,  10},	-- вход в пещеру
{-552.11, 14.53,  277.76,  25},	-- блокпост зона 1
{-556.86, 14.23,  326.10,  30},	-- блокпост зона 2
{-504.18, 0.06,  -151.02,  80},	-- пожарная часть
{-223.94, 28.01,  -153.08,  50},-- военная часть на холме зона 1
{-279.83, 27.83,  -166.45,  50},-- военная часть на холме зона 2
{-44.37, -3.25,  -258.60,  40},	-- фабрика
{-216.92,10.29,356.04,  15},	-- лагерь мутантов
{-219.40,31.84,281.27,  15},	-- лагерь мутантов
{-164.93,24.34,272.22,  15},	-- лагерь мутантов
{-299.29,3.18,296.28,  15},	-- лагерь мутантов
{-361.24,-3.48,360.70,  15},	-- лагерь мутантов
{-187.48,28.74,297.06,  15},	-- лагерь мутантов
{-246.76,0.92,417.41,  15},	-- лагерь мутантов
{-421.20,14.64,265.67,  15},	-- лагерь мутантов
{-451.951,37.87,172.14,  15},	-- лагерь мутантов
{-304.94,0.76,125.89,  15},	-- лагерь мутантов
{-244.99,1.32,88.66,  15},	-- лагерь мутантов
{-198.51,16.92,178.56,  15},	-- лагерь мутантов
{-109.53,10.40,105.08,  15},	-- лагерь мутантов
{-40.93,13.31,137.50,  15},	-- лагерь мутантов
{97.82,14.76,130.65,  15},	-- лагерь мутантов
{141.36,17.31,56.86,  15},	-- лагерь мутантов
{151.66,20.55,-55.48,  15},	-- лагерь мутантов
{32.90,8.70,-68.82,  15},	-- лагерь мутантов
{3.38,9.19,-67.56,  15},	-- лагерь мутантов
{32.45,-3.02,-2.68,  15},	-- лагерь мутантов
{-39.99,2.42,-4.89,  15},	-- лагерь мутантов
{53.03,2.69,59.02,  15},	-- лагерь мутантов
{82.19,4.51,-46.52,  15},	-- лагерь мутантов
{82.94,13.75,55.52,  15},	-- лагерь мутантов
{-49.96,9.89,-81.17,  15},	-- лагерь мутантов
{-91.32,11.26,-188.59,  15},	-- лагерь мутантов
{-125.85,-1.16,-314.14,  15},	-- лагерь мутантов
{-49.90,-3.20,-283.00,  15},	-- лагерь мутантов
{1.08,-4.06,-280.76,  15},	-- лагерь мутантов
{82.30,-19.73,-261.81,  15},	-- лагерь мутантов
{100.52,-21.88,-278.98,  15},	-- лагерь мутантов
{-20.39,-2.79,-261.95,  15},	-- лагерь мутантов
{-450.50,-8.16,-291.38,  15},	-- лагерь мутантов
{-569.10,-13.71,-287.24,  15},	-- лагерь мутантов
{-530.55,2.55,-99.22,  15},	-- лагерь мутантов
{-436.94,14.28,-32.69,  15},	-- лагерь мутантов
{-564.94,28.44,-15.62,  15},	-- лагерь мутантов
{-547.46,19.81,85.69,  15},	-- лагерь мутантов
{ 113.37,-8.35,386.91,  15},	-- лагерь мутантов
{-109.87,16.55,-136.51,  15},	-- лагерь мутантов
{-339.80,9.06,21.63,  15},	-- лагерь мутантов
{-204.83,3.75,406.61,  15},	-- лагерь мутантов
{109.69,-15.76,-253.13,  15},	-- лагерь мутантов
{-153.08,26.59,286.08,  15},	-- лагерь мутантов
{-417.38,30.43,81.05,  15},	-- лагерь мутантов	
{-192.48,7.28,-298.99,  10},	-- место спавна агентов
{-175.27,2.46,108.72,  10},	-- место спавна агентов
{-506.14,18.13,104.85,  10},	-- место спавна агентов
{-324.74,-6.31,348.77,  10},	-- место спавна агентов
{-563.61,13.95,216.63,  20},	-- место штурма кпп контрабандистами
{126.71,16.42,312.80,  30},	-- тело Зуба
{-266.10,16.30,235.21,  70},	-- пещера
{-347.78,12.40,146.66,  5},	-- Зона Маски
{17.23,-3.38,-84.91,  10},	-- место спавна секретного арта
{-51.07,9.10,-59.90,  40},	-- аномальное поле в деревне	
{126.53,15.60,-93.33,  5},	-- тело Понзыля
{119.95,16.90,101.24,  5},	-- тело 4
{-97.23,16.90,-162.52,  5},	-- тело 5
{112.39,-17.20,-261.18,  5},	-- тело 6
{-445.61,-7.40,-277.78,  5},	-- тело 7	
{-600.45,7.50,-63.10,  5},	-- тело 8
{-424.88,24.60,-1.29,  5},	-- тело 9	
{-236.59,3.20,115.25,  5},	-- тело 10
{-257.45,7.70,374.97,  5},	-- тело 11
{-457.20,24.30,122.01,  5},	-- тело 12
{82.91,39.20,233.08,  5},	-- тело 13
{-443.04,-0.50,-192.69,  5},	-- тело 14
{-290.38,18.90,-15.05,  5},	-- тело 15
{-25.24,2.70,1.09,  20},	-- стая квестовых кабанов в деревне
{-470.10,-3.72,-228.70,  25},	-- летающий телепорт на вышку
{53.93,17.50,-171.04,  10},	-- лагерь на холме1
{-552.70,27.60,-14.79,  10},	-- лагерь на холме2
{142.66,24.99,-168.50,  20},	-- трон Короля
{-184.99,1.68,105.86,  20},	-- логово Кошки
{4.00,33.60,222.58,  12},	-- разбитая вертушка на холме
{82.64,9.97,463.47,  15},	-- дружественный излом с сейфом
{-456.65,17.03,277.45,  8},	-- разведчик Саня
{-47.34,17.86,175.77,  10},	-- тайный лагерь контрабандистов
{8.05,  -0.30, -71.50, 1}		-- вход на территорию антенного комплекса
},			
}

local bad_sector_table = { --Скорее всего, это координаты, за пределами которых запрещено спавнить аномалии (места за пределами локаций).
	-- Кордон --- fixed by KamikaZze
	["l01_escape"] = {
		x1 = {  -89, -107, -160, 145,  10, -65, 136,  35, 373, -146,  83, -126, 145 },
		x2 = { -286, -150, -180,  90,  -5, -70, 125,  20, 346, -164,  29, -176, 117 },
		y1 = { -182, -400, -360, -50, -76, 115, 305, 670, -49, -341, 134, -360, 290 },
		y2 = { -100, -350, -344,  12, -55, 200, 325, 690, -15, -235, 182, -320, 335 },
	},
	-- Свалка --- fixed by KamikaZze
	["l02_garbage"] = {
		x1 = {   38,  -41,  68,   38, -230, 306,  -36,  125,  120,  -182 },
		x2 = {   25, -146,  15,   32, -306, 291,  -92,   51,   35,  -272 },
		y1 = { -271,   -9, 199, -323,  -32, 132, -250, -165,  140,  -177 },
		y2 = { -258,   29, 262, -289,  -13, 154, -195, -111,  185,  -133 },
	},
	-- Темная долина --- fixed by KamikaZze
	["l04_darkvalley"] = {
		x1 = { -131, -100,  -36,  191, 122,  51,  51, -29, -26, 20,   73,   71 },
		x2 = { -217, -155,  -53,  96,   82, -12, -33, -73, -32,  8,   35,   40 },
		y1 = { -211, -532, -547, -301, -20, -91,  25, -23, -22,  5, -249, -225 },
		y2 = { -175, -455, -536, -200,   8, -16,  50, -18,  25, 17, -208, -179 },
	},
	-- Агропром --- fixed by KamikaZze
	["l03_agroprom"] = {
		x1 = {   67, -188,  -89, 291, 255, -158 },
		x2 = { -100, -209, -211, 265, 220, -170 },
		y1 = {  -36,   78, -241,   0, -16,   90 },
		y2 = {   58,  102, -117,   5,   7,   98 },
	},
	-- Дикая территория --- fixed by KamikaZze
	["l06_rostok"] = {
		x1 = {  37,  -58, -226, -235, -218, -113, -215, -242 },
		x2 = {   9, -103, -235, -285, -242, -213, -297, -266 },
		y1 = { 117,  113,  135,   78,   29, -123,  119,    2 },
		y2 = { 156,  151,  165,  112,   64,  -49,  172,   24 },
	},
	-- Янтарь
	["l08_yantar"] = {
		x1 = {  39, 116, 150 },
		x2 = {  30,  55, 155 },
		y1 = { -55, -58, 58  },
		y2 = { -47, -34, 64  },
	},
	-- Армейские склады --- fixed by KamikaZze
	["l07_military"] = {
		x1 = { -305, -317, -198, -259, -324, -160,  -83, 104, 113, -203, -117,   75, -14, 77,  -2, -186,  92 },
		x2 = { -322, -347, -233, -277, -386, -195, -105,  85,  87, -247, -146, -141, -60,  0, -10, -202,  12 },
		y1 = {   55,   37,  185,  234,  371,  350,  207, 300, 160,   31,    7,  -62, -34, 10,   0,   35, 335 },
		y2 = {   67,   50,  211,  249,  411,  391,  235, 316, 184,   72,   37,  122, -10, 23, 109,   46, 403 },
	},
	-- Радар --- fixed by KamikaZze
	["l10_radar"] = {
		x1 = { 149, 390, 664, 404, 314 },
		x2 = {  75, 377, 609, 355, 297 },
		y1 = { -35, 141, 167, -11, -30 },
		y2 = { -20, 162, 200,  40, -15 },
	},
	-- Припять  --- fixed by KamikaZze
	["l11_pripyat"] = {
		x1 = {   31, 118, 115,  36,  18,   33 },
		x2 = {   11,  58,  96,  27, -17,  -15 },
		y1 = { -296,  -2, 110, 280, 191, -307 },
		y2 = { -266,  33, 159, 301, 210,  -60 },
	},
}


dangerous_acivated_arts = {}

function on_anomaly_spawn(obj)
	if is_not_anomaly(alife():object(obj:id())) then return end --НЕ аномалии не учитываем. Они сюда и не должны попадать, но на всякий случай.
	--
	--log3("[%s(%s)] obj:get_shape_radius(): [%s]", script_name(), obj:name(), obj:get_shape_radius())
	--
	anom_list[obj:id()] = { pos = obj:position(), clsid = obj:clsid(), radius = obj:get_shape_radius(), section = obj:section() }
	--log3("--[%s] Anomaly registered: [%s]", script_name(), obj:name())
end

function on_anomaly_net_destroy(obj)
	--log3("!![%s] Destroying anomaly: [%s]", script_name(), obj:name())
	anom_list[obj:id()] = nil
end

--Функция предназначена для определения ближайшей к точке аномалии
function get_nearest_anomaly_by_point(position)
	local dist, mindist, anomid = 0, 20, nil

	for id, anom in pairs(anom_list) do
		dist = position:distance_to(anom.pos) - anom.radius
		if dist < mindist then
			mindist = dist --Минимальное расстояние до аномалии
			anomid = id
		end
	end

	if anomid then
		--log3("[get_nearest_anomaly_by_point] dist from [%s] to [%s, %s, %s] = %s, OLD dist: [%s]", level.object_by_id(anomid):name(), position.x, position.y, position.z, mindist, (level.object_by_id(anomid):position()):distance_to(position))
		--log3("%s", debug.traceback())
		local anom_desc = anom_list[anomid]
		return true, anomid, anom_desc.pos, anom_desc.clsid, mindist, anom_desc.radius, anom_desc.section
	else
		return false
	end
end

function get_all_nearest_anomalies_by_point_in_radius(position, rads)
	local anom_out = {}
	for id, anom in pairs(anom_list) do
		local dist = position:distance_to(anom.pos) - anom.radius
		if dist < rads then
			--log3("[get_all_nearest_anomalies_by_point_in_radius] dist from [%s] to [%s] = [%s], max radius = [%s]", level.object_by_id(id):name(), position, dist, rads)
			--log3("%s", debug.traceback())
			anom_out[id] = { 
				pos = anom.pos,
				clsid = anom.clsid,
				dist = dist, --Расстояние до аномалии 
				radius = anom.radius,
				sect = anom.section
			}
		end
	end

	return anom_out
end


function bad_position(p_vector, lname) --Проверяем, попадает ли аномалия рядом с занятой позицией
	for k, v in pairs(position_forbidden) do
		if p_vector:distance_to(v) < 10 then
			return true
		end
	end

	return false
end

function bad_sector(p_vector, lname) --Видимо, нужно для того, чтобы аномалии за пределами локаций не спавнились.
	local bad_list = bad_sector_table[lname] --формируется по принципу x1>x2, y2>y1
	if not bad_list then return false end

	for k,v in pairs(bad_list.x1) do
		if (p_vector.x >= (bad_list.x2[k]) and (p_vector.x <= bad_list.x1[k])) and (p_vector.z >= (bad_list.y1[k]) and p_vector.z <= (bad_list.y2[k])) then
			return true
		end
	end

	return false
end

function bad_zone(p_vector) --Проверяем, попадает ли аномалия в зоны укрытий
	for _, id in pairs(ogse_hideouts.restrictor_list) do
		local sobj = alife():object(id)
		if sobj then
			local _, radius = ogse_hideouts.get_community_hide(sobj)
			if radius then
				if p_vector:distance_to(sobj.position) <= (tonumber(radius) + 10) then --Запрещено спавнить аномалии рядом с укрытиями
					return true
				end
			end
		end
	end

	return false
end

function bad_circle(pos)
	for k, v in ipairs( anti_spawn_zones ) do
		if pos:distance_to( v[ 1 ] ) <= v[ 2 ] then return true end
	end
	return false
end


function is_exclusion_location(lname) --Вернет true если на локации нельзя респавнить аномалии
	return DISABLE_ANOMS_RESPAWN or not level_anoms[lname]
end

function is_exclusion_anomaly(sobj)
	return excluded_anoms[sobj:section_name()] or excluded_anoms[sobj:name()]
end

function is_not_anomaly(sobj)
	return not_anomal_zones[sobj:section_name()]
end


function on_after_blowout()
	get_lists_inited = false
	add_anom()

	list_anom_id = {} --После обновления аномалий очищаем таблицы
	lvids_forbidden = {}
	position_forbidden = {}
end


function get_lists() --Вызывается из add_anom и generate_anoms, если нужно.
	list_anom_id = {}
	lvids_forbidden = { [db.actor:level_vertex_id()] = true }
	position_forbidden = { db.actor:position() }

	local lname = level.name()
	local sim = alife()
	local t = {}
	for id, sobj in sim:objects() do
		local sobj_lname = object_level_name( sobj )
		if IsAnomaly(sobj) then
			local status = get_anomaly_mode(sobj)
			local forbidden_anom = is_not_anomaly(sobj) or is_exclusion_anomaly(sobj)
			if status ~= "anom_off" then
				if not forbidden_anom then
					if not list_anom_id[sobj_lname] then
						list_anom_id[sobj_lname] = {}
					end
					list_anom_id[sobj_lname][id] = id
				end
			end
			if sobj_lname == lname then
				if forbidden_anom then
					lvids_forbidden[ sobj.m_level_vertex_id ] = true
					table.insert( position_forbidden, sobj.position )
				end
			else --Безопасно удалять аномалии можно только находясь на другой локации.
				if status == "anom_off" then
					table.insert( t, sobj )
				end
			end
		elseif isLc(sobj) then
			--Учитываем точки входа на локациях.
			local lc = sobj:get_level_changer()
			local dest_vertex = lc.dest_game_vertex_id
			local dest_lname  = alife():level_name(
				game_graph():vertex( dest_vertex ):level_id()
			)
			if dest_lname == lname then
				lvids_forbidden[lc.dest_level_vertex_id] = true
				table.insert(position_forbidden, lc.dest_position)
			end
			if sobj_lname == lname then --Учитываем точки ухода с локаций
				lvids_forbidden[ sobj.m_level_vertex_id ] = true
				table.insert( position_forbidden, sobj.position )
			end
		else --Не создавать аномалии там, где вообще хоть что-нибудь есть. Не важно, сталкер это или физический объект и тд.
			if sobj_lname == lname then
				lvids_forbidden[ sobj.m_level_vertex_id ] = true
				table.insert( position_forbidden, sobj.position )
			end
		end
	end

	for _, sobj in ipairs( t ) do
		alife():release( sobj )
	end

	get_lists_inited = true
	--log3("--[%s]Get_lists inited!", script_name())
end


--Отключаем динамические аномалии на всех локациях и спавним новые аномалии на текущей локации.
--На месте отключенной аномалии с какой-то вероятностью спавним артефакт.
function add_anom(levelname) --вызывается из anom_update() и сигналом из модуля выброса.
	levelname = levelname or level.name()
	if is_exclusion_location(levelname) then return end --Запрещено спавнить аномалии

	if not get_lists_inited then
		get_lists()
	end

	--log3("Called add_anom for level: [%s]", levelname)
	--log3("Debug list_anom_id = %s", list_anom_id)
	local list_loc_anom_id = list_anom_id[levelname]
	if list_loc_anom_id then
		for k,v in pairs(list_loc_anom_id) do
			local sobj = alife():object(v)
			if sobj then
				set_anomaly_mode(v, "anom_off")
			end
		end
	end

	if levelname == level.name() then --Спавним аномалии незамедлительно
		generate_anoms(levelname)
	else --аномалии будут заспавнены при переходе на локацию
		ogse.delete_var(script_name().."."..levelname)
		ogse.save_var(script_name().."."..levelname, 1.5) --1.5 = старые аномалии на локации отключены, новые будут заспавнены при переходе на локацию
	end
end

function spawn_anomaly( section, pos, lv, gv, shape )
	local sobj = alife():create( section, pos, lv, gv )
	ASSERT( sobj, "Can't generate_anomaly [%s], [%s], [%s], [%s]", section or "nil", pos or "nil", lv or "nil", gv or "nil")
    local pk = get_netpk( sobj, 1 )
    ASSERT( ( pk and pk:isOk() ), "can't read netpacket of %s", sobj:name() )
    local data = pk:get()
    if shape.shtype == 0 then
      data.shapes:addSphere(
        shape.radius, vector():set( unpack( shape.center ) )
      )
    else
      data.shapes:addBox(
        vector():set( unpack( shape.v1 ) ),
        vector():set( unpack( shape.v2 ) ),
        vector():set( unpack( shape.v3 ) ),
        vector():set( unpack( shape.offset ) )
      )
    end
	--level.map_add_object_spot(sobj.id, "green_location", sobj:name())
    pk:set( data )
	return alife():object(sobj.id)
end

--Создаёт набор аномалий на уровне
function generate_anoms(lname)
	if not get_lists_inited then
		get_lists()
	end

	--log3("--Called generate_anoms for level [%s]", lname)
	local v = level_anoms[lname]
	local rnd = math.floor(1 * math.random(v[1],v[2]) * (0.9+(level.get_game_difficulty()+1)*0.1))
	for i=1, rnd do
		local pos, new_lv, new_gv = anomaly_position_choice(lname)
		local section, shape = anomaly_section_choice(lname)
		ASSERT(shape.shtype ~= 0 or ( shape.radius and shape.radius > 0 ), "Incorrect shape radius for section [%s]", section)
		--shape.radius = shape.radius * get_float(section, "effective_radius", 1)
		spawn_anomaly( section, pos, new_lv, new_gv, shape )
		--log3("--[%s] Generated anomaly [%s] on level [%s]", script_name(), section, lname)

		lvids_forbidden[new_lv] = true
		table.insert(position_forbidden, pos)
		
	end
	ogse.delete_var(script_name().."."..lname)
	ogse.save_var(script_name().."."..lname, 1) --1 = аномалии на локации обновлены.
end

function anom_update()
	local lname = level.name()
	local bad_pos_tbl = bad_circle_table[lname]
	if bad_pos_tbl then
		for _, pos in pairs(bad_pos_tbl) do
			table.insert( anti_spawn_zones, { vector():set( pos[ 1 ], pos[ 2 ], pos[ 3 ] ), pos[ 4 ] } )
		end
		--log3("~~anti_spawn_zones_tbl: %s", anti_spawn_zones)
	end

	if has_alife_info("blowout") then return end --Во время выброса делать нечего

	for k,_ in pairs(level_anoms) do
		local anom_chek = tonumber(ogse.load_var_safe(script_name().."."..k) or 2) --Если в хранилище нет данных по аномалиям на локации, значит запустили игру в первый раз и аномалии надо обновить.
		if anom_chek == 2 then --Требуется обновление после выброса
			add_anom(k) --на текущей локации аномалии обновятся сразу, на остальных - будут обновлены только при переходе на локацию
		elseif anom_chek == 1.5 and k == lname and not is_exclusion_location(k) then --Новые аномалии будут заспавнены только при переходе на локацию.
			generate_anoms(lname)
		end
	end

	list_anom_id = {} --После обновления аномалий очищаем таблицы
	lvids_forbidden = {}
	position_forbidden = {}
end

--Поднимаем флаги выброса для локаций
function blow_flags() --вызывается из менеджера выброса
	for k,_ in pairs(level_anoms) do
		ogse.delete_var(script_name().."."..k)
		ogse.save_var(script_name().."."..k, 2) --2 = требуется обновление аномалий на локации
	end
end


--Получаем статус аномалии
function get_anomaly_mode(sobj)
	local ini = sobj:spawn_ini()
	if ini and ini:section_exist( "m_anom" ) then
		return get_string( "m_anom", "status", "", ini )
	end

	return ""
end

--Устанавливаем статус аномалии. По факту статус можно установить один - anom_off. В других статусах нет надобности.
function set_anomaly_mode(anom_id, status)
	local sobj = alife():object(anom_id)
	if not sobj then return end

	local ini = sobj:spawn_ini()
	ini.readonly = false
	ini:w_string( "m_anom", "status", status )
	sobj:save_spawn_ini()

	ASSERT(status == "anom_off", "strange anomaly status: [%s]", status)

	if status == "anom_off" then
		anom_list[anom_id] = nil
		local obj = level.object_by_id(anom_id)
		if obj then
			obj:disable_anomaly()
			dsh_anomaly_detector.remove_restriction(anom_id)
		end
	end
	--log3("[%s.set_anomaly_mode] New status for anom [%s] = [%s]. Level: [%s]", script_name(), sobj:name(), status, object_level_name(sobj))
end


--Эта функция парсит строку из конфига аномалии и выбирает какой арт спавнить
function parse_string_arts(sect) --Перенесено из скрипта ogse_death_artefact
	local string_arts = get_string(sect, "artefacts")
	if not string_arts then return false end

	local arts_table = {}
	for key, value, dec in string.gmatch( string_arts, "%s*([%w_%-.\\]+)%s*,%s*(%d).(%d*)%s*" ) do
		local artefact = { art = key, val = tonumber(value.."."..dec) }
		table.insert(arts_table, artefact)
	end
	if #arts_table > 0 then
		--log3("[%s] arts_table for anom [%s] before sort: %s", script_name(), sect, arts_table)
		table.sort(arts_table,function(a,b) return a.val < b.val end) --Секции артов должны находиться в таблице в порядке от меньшей вероятности спавна к большей.
		--log3("[%s] arts_table for anom [%s] after sort: %s", script_name(), sect, arts_table)

		local rnd = math.random()
		for _, value in ipairs(arts_table) do
			if rnd <= value.val then
				return value.art
			end
		end
	end

	return false
end

-- Рожание артефактов в Выброс
local game_difficulty = level.get_game_difficulty()


function anomaly_position_choice(lname)
	ASSERT( lname == level.name(), "level.vertex_count() work only on current level!" )

	local lvx = level.vertex_count() - 1
	local new_lv, pos

	repeat --Подбираем свободный level_vertex и position
		new_lv = math.random(lvx)
		pos = level.vertex_position(new_lv)
	until not lvids_forbidden[new_lv] and not (
		   bad_sector(pos, lname) --Скорее всего, места за пределами локаций
		or bad_position(pos, lname) --Монстры, НПС, актор, точки переходов, квестовые аномалии и тп...
		or bad_zone(pos, lname) --Укрытия
		or bad_circle(pos, lname) --Места, в которых по каким-то причинам нельзя спавнить аномалии (лагеря, квестовые сцены и тд.). Настраиваются вручную.
	)

	local new_gv = cross_table():vertex( new_lv ):game_vertex_id()

	return pos, new_lv, new_gv
end


local anom_types = {
	l01_escape = {
		mosquito_bald     = 0.3,
		gravi_zone        = 0.25,
		mincer            = 0.25,
		witches_galantine = 0.1,
		zharka_static     = 0.1
	},
	l02_garbage = {
		mosquito_bald     = 0.2,
		gravi_zone        = 0.2,
		mincer            = 0.2,
		witches_galantine = 0.2,
		zharka_static     = 0.15,
		buzz              = 0.05
	},
	l03_agroprom = {
		mosquito_bald     = 0.2,
		gravi_zone        = 0.2,
		mincer            = 0.2,
		witches_galantine = 0.25,
		zharka_static     = 0.1,
		buzz              = 0.05
	},
	l04_darkvalley = {
		mosquito_bald     = 0.2,
		gravi_zone        = 0.2,
		mincer            = 0.2,
		witches_galantine = 0.2,
		zharka_static     = 0.15,
		buzz              = 0.05
	},
	l05_bar = {
		mosquito_bald     = 0.2,
		gravi_zone        = 0.2,
		mincer            = 0.3,
		witches_galantine = 0.15,
		zharka_static     = 0.15
	},
	l06_rostok = {
		mosquito_bald     = 0.1,
		gravi_zone        = 0.1,
		mincer            = 0.15,
		witches_galantine = 0.25,
		zharka_static     = 0.4
	},
	l07_military = {
		mosquito_bald     = 0.1,
		gravi_zone        = 0.2,
		mincer            = 0.2,
		witches_galantine = 0.3,
		zharka_static     = 0.15,
		buzz              = 0.05
	},
	l08_yantar = {
		mosquito_bald     = 0.05,
		gravi_zone        = 0.15,
		mincer            = 0.15,
		witches_galantine = 0.25,
		zharka_static     = 0.15,
		buzz              = 0.25
	},
	l10_radar = {
		mosquito_bald     = 0.1,
		gravi_zone        = 0.2,
		mincer            = 0.2,
		witches_galantine = 0.2,
		zharka_static     = 0.2,
		buzz              = 0.1
	},
	l11_pripyat = {
		mosquito_bald     = 0.1,
		gravi_zone        = 0.2,
		mincer            = 0.2,
		witches_galantine = 0.2,
		zharka_static     = 0.2,
		buzz              = 0.1
	},
	l12_stancia = {
		mosquito_bald     = 0.17,
		gravi_zone        = 0.17,
		mincer            = 0.17,
		witches_galantine = 0.17,
		zharka_static     = 0.17,
		buzz              = 0.15
	},
	other = {
		mosquito_bald     = 0.2,
		gravi_zone        = 0.2,
		mincer            = 0.2,
		witches_galantine = 0.2,
		zharka_static     = 0.2
	}
}

local anom_power = {
	l01_escape =     {{postfix = "_weak", val =   1}, {postfix = "_average", val = 0.3}, {postfix = "_strong", val = 0.01}},
	l02_garbage =    {{postfix = "_weak", val =   1}, {postfix = "_average", val = 0.6}, {postfix = "_strong", val = 0.05}},
	l03_agroprom =   {{postfix = "_weak", val = 0.8}, {postfix = "_average", val =   1}, {postfix = "_strong", val =  0.2}},
	l04_darkvalley = {{postfix = "_weak", val = 0.7}, {postfix = "_average", val =   1}, {postfix = "_strong", val =  0.3}},
	l05_bar =        {{postfix = "_weak", val =   1}, {postfix = "_average", val = 0.6}, {postfix = "_strong", val =  0.1}},
	l06_rostok =     {{postfix = "_weak", val = 0.6}, {postfix = "_average", val =   1}, {postfix = "_strong", val =  0.3}},
	l07_military =   {{postfix = "_weak", val = 0.3}, {postfix = "_average", val =   1}, {postfix = "_strong", val =  0.6}},
	l08_yantar =     {{postfix = "_weak", val = 0.7}, {postfix = "_average", val =   1}, {postfix = "_strong", val =  0.3}},
	l10_radar =      {{postfix = "_weak", val = 0.2}, {postfix = "_average", val = 0.6}, {postfix = "_strong", val =    1}},
	l11_pripyat =    {{postfix = "_weak", val = 0.1}, {postfix = "_average", val = 0.5}, {postfix = "_strong", val =    1}},
	l12_stancia =    {{postfix = "_weak", val = 0.1}, {postfix = "_average", val = 0.4}, {postfix = "_strong", val =    1}},
	other =          {{postfix = "_weak", val = 0.6}, {postfix = "_average", val =   1}, {postfix = "_strong", val =  0.3}}
}

local anoms_sections = {
	buzz              = {"buzz",              {shtype=0, radius=1.5, center={0,0,0}}},
	gravi_zone        = {"gravi_zone",        {shtype=0, radius=3,   center={0,0,0}}},
	mincer            = {"mincer",            {shtype=0, radius=3.5,   center={0,0,0}}},
	mosquito_bald     = {"mosquito_bald",     {shtype=0, radius=3,   center={0,0,0}}},
	witches_galantine = {"witches_galantine", {shtype=0, radius=4,   center={0,0,0}}},
	zharka_static     = {"zharka_static",     {shtype=1, v1={1,0,0}, v2={0,7,0}, v3={0,0,1}, offset={0,0,0}}}
}

local anom_prefix = "noartf_" --KRodin: Префикс не влияет на спавн артов, нужен только для того чтобы отличить аномалии созданные выбросом от всех остальных аномалий.
function anomaly_section_choice(levelname)
	local anom_to_spawn, name_anom_to_spawn, postfix_anom_to_spawn, anom_table_name
	local anom_table_name = anom_types[levelname] or anom_types.other
	local type_choose = math.random()
	local b1, b2 = 0.0, 0.0
	for k,v in pairs(anom_table_name) do
		b2 = b2 + v
		if type_choose >= b1 and type_choose <= b2 then
			name_anom_to_spawn = k
			break
		end
		b1 = b2
	end

	local anom_table_postfix = anom_power[levelname] or anom_power.other
	local spawn_choose = math.random()
	local low_level = 0.0

	table.sort(anom_table_postfix,function(a,b) return a.val < b.val end)

	for key, value in pairs(anom_table_postfix) do
		if spawn_choose < value.val and spawn_choose >= low_level then
			postfix_anom_to_spawn = value.postfix
		end
		low_level = value.val
	end

	if name_anom_to_spawn and postfix_anom_to_spawn then
		anom_to_spawn = anom_prefix .. name_anom_to_spawn .. postfix_anom_to_spawn
	end

	return anom_to_spawn, anoms_sections[name_anom_to_spawn][2]
end


function delete_anomalies_in_radius(radius)
	local sim = alife()
	local actorPosition = db.actor:position()
	for i=1,65534 do
		local object = level.object_by_id(i)
		if object and IsAnomaly(object) then
				if object:position():distance_to(actorPosition) < radius then
						local anomaly = sim:object(i)
						if anomaly then sim:release(anomaly) end
			end
		end
	end
end